spring:
  datasource:
    url: jdbc:mysql://******:3306/phone?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: *****
  #关闭thymeleaf cache
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.hongdou.cvs.pojo